### ISSUE TITLE
common.py has no attribute 'batched_index_select'

### ISSUE THREAD

**Issue by raychl94** [OwXiaoM/_PCS#1]
attention.py
        # group elements with same hash code by sorting
        _, indices = hash_codes.sort(dim=-1)  # [N,n_hashes*H*W]
        _, undo_sort = indices.sort(dim=-1)  # undo_sort to recover original order
        mod_indices = (indices % L)  # now range from (0->H*W)
        x_embed_sorted = common.batched_index_select(x_embed, mod_indices)  # [N,n_hashes*H*W,C]  #line 65
        y_embed_sorted = common.batched_index_select(y_embed, mod_indices)  # [N,n_hashes*H*W,C] #line 66
你好，common.py文件里没有'batched_index_select' ，以至于运用attention.py文件时报错，是我遗漏了什么吗？
感谢您的精彩工作！

**Comment by OwXiaoM** [comment]
您好，感谢您的提醒，这个是NLSN中使用的方法，我将之后更新一下，您可以先试用原作者的代码。https://github.com/HarukiYqM/Non-Local-Sparse-Attention/blob/fb3d422558328135c6355404053c2dc9654b699e/src/model/common.py#L8
