### ISSUE TITLE
Setup test

### ISSUE THREAD

**Issue by ezrafield** [OwXiaoM/_PCS#2]
where I can set the test datasets to run the model?
![image](https://github.com/OwXiaoM/PCS/assets/52470344/a20f44aa-2f43-4427-9d3a-e8e78194550d)

**Comment by ezrafield** [comment]
oh, need change --dir_data, thanks

**Comment by OwXiaoM** [comment]
Hi, it seems you have find the problem, nice work. Actually we inherit the framework of EDSR, so they are the same settings.
